using Sharpliner.AzureDevOps.Expressions;
using YamlDotNet.Serialization;

namespace Sharpliner.AzureDevOps.Tasks;

/// <summary>
/// Publishes SARIF results to GitHub Advanced Security for Azure DevOps using the
/// <c>AdvancedSecurity-Publish@1</c> Azure DevOps task.
/// See <see href="https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/advanced-security-publish-v1?view=azure-pipelines">the official task reference</see>
/// and <see href="https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/advanced-security-publish-v1.md">the official task definition</see>.
/// </summary>
public record AdvancedSecurityPublishTask : AzureDevOpsTask
{
    /// <summary>
    /// Initializes a new instance of the <see cref="AdvancedSecurityPublishTask"/> class.
    /// </summary>
    public AdvancedSecurityPublishTask()
        : base("AdvancedSecurity-Publish@1")
    {
        DisplayName = "Advanced Security Publish Results";
    }

    /// <summary>
    /// Specifies the directory containing SARIF files to publish.
    /// Defaults to <c>$(Build.SourcesDirectory)</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? SarifsInputDirectory
    {
        get => GetExpression<string>("SarifsInputDirectory");
        init => SetProperty("SarifsInputDirectory", value);
    }

    /// <summary>
    /// Enables recursive scanning for SARIF files in subdirectories of <see cref="SarifsInputDirectory"/>.
    /// Defaults to <code>false</code>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<bool>? EnableRecursiveScanning
    {
        get => GetExpression<bool>("EnableRecursiveScanning");
        init => SetProperty("EnableRecursiveScanning", value);
    }

    /// <summary>
    /// Specifies the category assigned to the SARIF results. This input is ignored for SARIF files generated by CodeQL.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? Category
    {
        get => GetExpression<string>("Category");
        init => SetProperty("Category", value);
    }

    /// <summary>
    /// Waits for the Advanced Security service to process the published SARIF files.
    /// Defaults to <code>false</code>. Set this to <code>true</code> to use
    /// <see cref="WaitForProcessingInterval"/> and <see cref="WaitForProcessingTimeout"/>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<bool>? WaitForProcessing
    {
        get => GetExpression<bool>("WaitForProcessing");
        init => SetProperty("WaitForProcessing", value);
    }

    /// <summary>
    /// Specifies the polling interval in seconds while waiting for SARIF processing.
    /// This input is used only when <see cref="WaitForProcessing"/> is <code>true</code>.
    /// Defaults to <c>5</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? WaitForProcessingInterval
    {
        get => GetExpression<string>("WaitForProcessingInterval");
        init => SetProperty("WaitForProcessingInterval", value);
    }

    /// <summary>
    /// Specifies the maximum time in seconds to wait for SARIF processing.
    /// This input is used only when <see cref="WaitForProcessing"/> is <code>true</code>.
    /// Defaults to <c>120</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? WaitForProcessingTimeout
    {
        get => GetExpression<string>("WaitForProcessingTimeout");
        init => SetProperty("WaitForProcessingTimeout", value);
    }
}
