using System;
using Sharpliner.AzureDevOps.Expressions;
using YamlDotNet.Serialization;

namespace Sharpliner.AzureDevOps.Tasks;

/// <summary>
/// Base class for strongly typed Azure Container Apps deployment tasks.
/// More details can be found in the
/// <see href="https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-container-apps-v1?view=azure-pipelines">official Azure DevOps pipelines documentation</see>
/// and the <see href="https://raw.githubusercontent.com/microsoft/azure-pipelines-tasks/master/Tasks/AzureContainerAppsV1/task.json">official AzureContainerAppsV1 task specification audited on 2026-08-31</see>.
/// </summary>
public abstract record AzureContainerAppsTask : AzureDevOpsTask
{
    /// <summary>
    /// Required. Azure Resource Manager service connection for the deployment.
    /// The official input name is <c>connectedServiceNameARM</c>; <c>azureSubscription</c> is its YAML alias and is emitted for compatibility with existing Sharpliner output.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? AzureSubscription
    {
        get => GetExpression<string>("azureSubscription");
        init => SetProperty("azureSubscription", value);
    }

    /// <summary>
    /// Optional. Current working directory where the script is run.
    /// Empty is the root of the repo (build) or artifacts (release), which is <c>$(System.DefaultWorkingDirectory)</c>.
    /// The official input name is <c>cwd</c>; <c>workingDirectory</c> is its YAML alias and is emitted for compatibility with existing Sharpliner output.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? WorkingDirectory
    {
        get => GetExpression<string>("workingDirectory");
        init => SetProperty("workingDirectory", value);
    }

    /// <summary>
    /// Optional. The name of the Azure Container App that will be created or updated.
    /// If not provided, this value is generated by the task.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? ContainerAppName
    {
        get => GetExpression<string>("containerAppName");
        init => SetProperty("containerAppName", value);
    }

    /// <summary>
    /// Optional. Existing resource group for the container app. If omitted, the task determines or creates one.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? ResourceGroup
    {
        get => GetExpression<string>("resourceGroup");
        init => SetProperty("resourceGroup", value);
    }

    /// <summary>
    /// Optional. Existing Container App environment name. If omitted, the task determines or creates one.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? ContainerAppEnvironment
    {
        get => GetExpression<string>("containerAppEnvironment");
        init => SetProperty("containerAppEnvironment", value);
    }

    /// <summary>
    /// Optional. The designated target port for the application.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? TargetPort
    {
        get => GetExpression<string>("targetPort");
        init => SetProperty("targetPort", value);
    }

    /// <summary>
    /// Optional. The location where the container app and related resources are deployed.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? Location
    {
        get => GetExpression<string>("location");
        init => SetProperty("location", value);
    }

    /// <summary>
    /// Optional. Space-separated environment variables in <c>key=value</c> format.
    /// Prefix values with <c>secretref:</c> to reference secrets.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? EnvironmentVariables
    {
        get => GetExpression<string>("environmentVariables");
        init => SetProperty("environmentVariables", value);
    }

    /// <summary>
    /// Optional. Ingress setting.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<AzureContainerAppIngress>? Ingress
    {
        get => GetExpression<AzureContainerAppIngress>("ingress");
        init => SetProperty("ingress", value);
    }

    /// <summary>
    /// Optional. Set to <see cref="AzureContainerAppKind.FunctionApp"/> to enable built-in support and autoscaling for Azure Functions on Container Apps.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<AzureContainerAppKind>? Kind
    {
        get => GetExpression<AzureContainerAppKind>("kind");
        init => SetProperty("kind", value);
    }

    /// <summary>
    /// Optional. If set to true, telemetry collection by this task is disabled.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<bool>? DisableTelemetry
    {
        get => GetExpression<bool>("disableTelemetry");
        init => SetProperty("disableTelemetry", value);
    }

    protected AzureContainerAppsTask(string taskName, AdoExpression<string> azureSubscription)
        : base(taskName)
    {
        AzureSubscription = azureSubscription;
        DisplayName = "Azure Container Apps Deploy";
    }
}

/// <summary>
/// Base class for Azure Container Apps tasks that build an image from source before deployment.
/// This mode models the <c>appSourcePath</c> + <c>acrName</c> path.
/// </summary>
public abstract record AzureContainerAppsFromSourceTask : AzureContainerAppsTask
{
    /// <summary>
    /// Required for source-based deployments. Absolute path of application source code on the agent.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? AppSourcePath
    {
        get => GetExpression<string>("appSourcePath");
        init => SetProperty("appSourcePath", value);
    }

    /// <summary>
    /// Required for source-based deployments. Name of the Azure Container Registry to push the built image to.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? AcrName
    {
        get => GetExpression<string>("acrName");
        init => SetProperty("acrName", value);
    }

    /// <summary>
    /// Optional. ACR username used for registry authentication.
    /// If omitted, the task can authenticate by generating an access token via <c>az acr login</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? AcrUsername
    {
        get => GetExpression<string>("acrUsername");
        init => SetProperty("acrUsername", value);
    }

    /// <summary>
    /// Optional. ACR password used for registry authentication.
    /// If omitted, the task can authenticate by generating an access token via <c>az acr login</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? AcrPassword
    {
        get => GetExpression<string>("acrPassword");
        init => SetProperty("acrPassword", value);
    }

    /// <summary>
    /// Optional. Relative path to the Dockerfile under <see cref="AppSourcePath"/>.
    /// If omitted, the task tries a root <c>Dockerfile</c> and then the Oryx++ Builder.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? DockerfilePath
    {
        get => GetExpression<string>("dockerfilePath");
        init => SetProperty("dockerfilePath", value);
    }

    /// <summary>
    /// Optional. Custom image name to build and push to ACR.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? ImageToBuild
    {
        get => GetExpression<string>("imageToBuild");
        init => SetProperty("imageToBuild", value);
    }

    /// <summary>
    /// Optional. Image name to deploy. If omitted, the built image name is used.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? ImageToDeploy
    {
        get => GetExpression<string>("imageToDeploy");
        init => SetProperty("imageToDeploy", value);
    }

    /// <summary>
    /// Optional. Platform runtime stack in the format <c>&lt;platform&gt;:&lt;version&gt;</c> for Oryx builds.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? RuntimeStack
    {
        get => GetExpression<string>("runtimeStack");
        init => SetProperty("runtimeStack", value);
    }

    protected AzureContainerAppsFromSourceTask(string taskName, AdoExpression<string> azureSubscription, AdoExpression<string> appSourcePath, AdoExpression<string> acrName)
        : base(taskName, azureSubscription)
    {
        AppSourcePath = appSourcePath;
        AcrName = acrName;
    }
}

/// <summary>
/// Base class for Azure Container Apps tasks that deploy an already built image.
/// This mode models the <c>imageToDeploy</c> path.
/// </summary>
public abstract record AzureContainerAppsFromImageTask : AzureContainerAppsTask
{
    /// <summary>
    /// Required for image-based deployments. Full image reference including registry server.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? ImageToDeploy
    {
        get => GetExpression<string>("imageToDeploy");
        init => SetProperty("imageToDeploy", value);
    }

    /// <summary>
    /// Optional. Name of the Azure Container Registry associated with the deployed image.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? AcrName
    {
        get => GetExpression<string>("acrName");
        init => SetProperty("acrName", value);
    }

    /// <summary>
    /// Optional. ACR username used for registry authentication.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? AcrUsername
    {
        get => GetExpression<string>("acrUsername");
        init => SetProperty("acrUsername", value);
    }

    /// <summary>
    /// Optional. ACR password used for registry authentication.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? AcrPassword
    {
        get => GetExpression<string>("acrPassword");
        init => SetProperty("acrPassword", value);
    }

    protected AzureContainerAppsFromImageTask(string taskName, AdoExpression<string> azureSubscription, AdoExpression<string> imageToDeploy)
        : base(taskName, azureSubscription)
    {
        ImageToDeploy = imageToDeploy;
    }
}

/// <summary>
/// Base class for Azure Container Apps tasks that deploy using a YAML configuration file.
/// This mode models the <c>yamlConfigPath</c> path.
/// </summary>
public abstract record AzureContainerAppsFromYamlTask : AzureContainerAppsTask
{
    /// <summary>
    /// Required for YAML-based deployments. Full path on the agent to the Container Apps YAML configuration file.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? YamlConfigPath
    {
        get => GetExpression<string>("yamlConfigPath");
        init => SetProperty("yamlConfigPath", value);
    }

    protected AzureContainerAppsFromYamlTask(string taskName, AdoExpression<string> azureSubscription, AdoExpression<string> yamlConfigPath)
        : base(taskName, azureSubscription)
    {
        YamlConfigPath = yamlConfigPath;
    }
}

/// <summary>
/// Strongly typed source-build-and-deploy task using <c>AzureContainerApps@1</c>.
/// </summary>
public record AzureContainerAppsV1FromSourceTask : AzureContainerAppsFromSourceTask
{
    public AzureContainerAppsV1FromSourceTask(AdoExpression<string> azureSubscription, AdoExpression<string> appSourcePath, AdoExpression<string> acrName)
        : base("AzureContainerApps@1", azureSubscription, appSourcePath, acrName)
    {
    }
}

/// <summary>
/// Strongly typed image-deploy task using <c>AzureContainerApps@1</c>.
/// </summary>
public record AzureContainerAppsV1FromImageTask : AzureContainerAppsFromImageTask
{
    public AzureContainerAppsV1FromImageTask(AdoExpression<string> azureSubscription, AdoExpression<string> imageToDeploy)
        : base("AzureContainerApps@1", azureSubscription, imageToDeploy)
    {
    }
}

/// <summary>
/// Strongly typed YAML-deploy task using <c>AzureContainerApps@1</c>.
/// </summary>
public record AzureContainerAppsV1FromYamlTask : AzureContainerAppsFromYamlTask
{
    public AzureContainerAppsV1FromYamlTask(AdoExpression<string> azureSubscription, AdoExpression<string> yamlConfigPath)
        : base("AzureContainerApps@1", azureSubscription, yamlConfigPath)
    {
    }
}

/// <summary>
/// Strongly typed source-build-and-deploy task using <c>AzureContainerApps@0</c>.
/// </summary>
[Obsolete("AzureContainerApps@0 is deprecated by Azure Pipelines. Prefer AzureContainerApps@1.")]
public record AzureContainerAppsV0FromSourceTask : AzureContainerAppsFromSourceTask
{
    public AzureContainerAppsV0FromSourceTask(AdoExpression<string> azureSubscription, AdoExpression<string> appSourcePath, AdoExpression<string> acrName)
        : base("AzureContainerApps@0", azureSubscription, appSourcePath, acrName)
    {
    }
}

/// <summary>
/// Strongly typed image-deploy task using <c>AzureContainerApps@0</c>.
/// </summary>
[Obsolete("AzureContainerApps@0 is deprecated by Azure Pipelines. Prefer AzureContainerApps@1.")]
public record AzureContainerAppsV0FromImageTask : AzureContainerAppsFromImageTask
{
    public AzureContainerAppsV0FromImageTask(AdoExpression<string> azureSubscription, AdoExpression<string> imageToDeploy)
        : base("AzureContainerApps@0", azureSubscription, imageToDeploy)
    {
    }
}

/// <summary>
/// Strongly typed YAML-deploy task using <c>AzureContainerApps@0</c>.
/// </summary>
[Obsolete("AzureContainerApps@0 is deprecated by Azure Pipelines. Prefer AzureContainerApps@1.")]
public record AzureContainerAppsV0FromYamlTask : AzureContainerAppsFromYamlTask
{
    public AzureContainerAppsV0FromYamlTask(AdoExpression<string> azureSubscription, AdoExpression<string> yamlConfigPath)
        : base("AzureContainerApps@0", azureSubscription, yamlConfigPath)
    {
    }
}

/// <summary>
/// Ingress values supported by Azure Container Apps task inputs.
/// </summary>
public enum AzureContainerAppIngress
{
    /// <summary>
    /// Internet or VNET-reachable ingress.
    /// </summary>
    [YamlMember(Alias = "external")]
    External,

    /// <summary>
    /// Ingress reachable only from within the Container Apps environment.
    /// </summary>
    [YamlMember(Alias = "internal")]
    Internal,

    /// <summary>
    /// Disable ingress for the Container App.
    /// </summary>
    [YamlMember(Alias = "disabled")]
    Disabled,
}

/// <summary>
/// Optional kind values supported by Azure Container Apps task inputs.
/// </summary>
public enum AzureContainerAppKind
{
    /// <summary>
    /// Enables built-in support and autoscaling for Azure Functions on Container Apps.
    /// </summary>
    [YamlMember(Alias = "functionapp")]
    FunctionApp,
}
