using Sharpliner.AzureDevOps.Expressions;
using YamlDotNet.Serialization;

namespace Sharpliner.AzureDevOps.Tasks;

/// <summary>
/// Deploys a web, mobile, or API app to Azure App Service using the <c>AzureRmWebAppDeployment@5</c> task.
/// More details can be found in the <see href="https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v5?view=azure-pipelines">official Azure DevOps pipelines documentation</see>
/// and the <see href="https://raw.githubusercontent.com/microsoft/azure-pipelines-tasks/master/Tasks/AzureRmWebAppDeploymentV5/task.json">official AzureRmWebAppDeploymentV5 task specification audited on 2026-08-31</see>.
/// <para>
/// Older majors (<c>AzureRmWebAppDeployment@4</c> and below) accept the same inputs apart from the Linux deployment options
/// (<c>DeploymentTypeLinux</c> and <c>CleanDeploymentFlag</c>) which were introduced in the fifth major, so only <c>AzureRmWebAppDeployment@5</c> is modelled.
/// </para>
/// </summary>
public abstract record AzureRmWebAppDeploymentTask : AzureDevOpsTask
{
    /// <summary>
    /// Required. Service connection type used to deploy the web app. Default value: <c>AzureRM</c>.
    /// The value is defined by the concrete task type and cannot be changed.
    /// </summary>
    [YamlIgnore]
    public AzureAppServiceConnectionType ConnectionType
    {
        get => GetEnum("ConnectionType", AzureAppServiceConnectionType.AzureRM);
        private init => SetProperty("ConnectionType", value);
    }

    /// <summary>
    /// Required. File path to the package or a folder containing App Service contents generated by MSBuild,
    /// or a compressed zip, war or jar file. Default value: <c>$(System.DefaultWorkingDirectory)/**/*.zip</c>.
    /// The official input name is <c>Package</c>; <c>packageForLinux</c> is its documented YAML alias.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? Package
    {
        get => GetExpression<string>("packageForLinux");
        init => SetProperty("packageForLinux", value);
    }

    /// <summary>
    /// Optional. Generates a standard <c>web.config</c> and deploys it to the App Service when the application does not have one.
    /// The values follow the syntax <c>-key value</c>, for example <c>-Handler iisnode -NodeStartFile server.js -appType node</c>.
    /// Not supported for container app types, Linux app types or <c>.war</c> packages.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? WebConfigParameters
    {
        get => GetExpression<string>("WebConfigParameters");
        init => SetProperty("WebConfigParameters", value);
    }

    /// <summary>
    /// Optional. Default value: <c>false</c>. Runs the config transforms for <c>*.Release.config</c> and <c>*.&lt;EnvironmentName&gt;.config</c>
    /// on the <c>*.config</c> file. Config transforms run prior to the variable substitution and are supported on Windows only.
    /// The official input name is <c>XmlTransformation</c>; <c>enableXmlTransform</c> is its documented YAML alias.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<bool>? XmlTransformation
    {
        get => GetExpression<bool>("enableXmlTransform", false);
        init => SetProperty("enableXmlTransform", value);
    }

    /// <summary>
    /// Optional. Default value: <c>false</c>. Substitutes variables defined in the pipeline into the <c>appSettings</c>,
    /// <c>applicationSettings</c> and <c>connectionStrings</c> sections of any config file and <c>parameters.xml</c>.
    /// Variable substitution runs after the config transforms.
    /// The official input name is <c>XmlVariableSubstitution</c>; <c>enableXmlVariableSubstitution</c> is its documented YAML alias.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<bool>? XmlVariableSubstitution
    {
        get => GetExpression<bool>("enableXmlVariableSubstitution", false);
        init => SetProperty("enableXmlVariableSubstitution", value);
    }

    /// <summary>
    /// Optional. New line separated list of JSON files (relative to the root folder) in which the variable values are substituted.
    /// Nested or hierarchical JSON variables are specified using JSONPath expressions, for example <c>Data.DefaultConnection.ConnectionString</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? JsonFiles
    {
        get => GetExpression<string>("JSONFiles");
        init => SetProperty("JSONFiles", value);
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="AzureRmWebAppDeploymentTask"/> class.
    /// </summary>
    /// <param name="connectionType">Service connection type used to deploy the web app.</param>
    protected AzureRmWebAppDeploymentTask(AzureAppServiceConnectionType connectionType)
        : base("AzureRmWebAppDeployment@5")
    {
        ConnectionType = connectionType;
    }
}

/// <summary>
/// Deploys to Azure App Service using a publish profile created in Visual Studio (<c>ConnectionType: PublishProfile</c>).
/// More details can be found in the <see href="https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v5?view=azure-pipelines">official Azure DevOps pipelines documentation</see>.
/// </summary>
public record AzureRmWebAppDeploymentPublishProfileTask : AzureRmWebAppDeploymentTask
{
    /// <summary>
    /// Required when <c>ConnectionType = PublishProfile</c>. Path of the publish profile created in Visual Studio.
    /// Default value: <c>$(System.DefaultWorkingDirectory)/**/*.pubxml</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? PublishProfilePath
    {
        get => GetExpression<string>("PublishProfilePath");
        init => SetProperty("PublishProfilePath", value);
    }

    /// <summary>
    /// Required when <c>ConnectionType = PublishProfile</c>. Password of the publish profile.
    /// It is recommended to store the password in a secret variable and reference it here, for example <c>$(Password)</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? PublishProfilePassword
    {
        get => GetExpression<string>("PublishProfilePassword");
        init => SetProperty("PublishProfilePassword", value);
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="AzureRmWebAppDeploymentPublishProfileTask"/> class with required properties.
    /// </summary>
    /// <param name="publishProfilePath">Path of the publish profile created in Visual Studio.</param>
    /// <param name="publishProfilePassword">Password of the publish profile.</param>
    /// <param name="package">File path to the package or a folder containing the App Service contents.</param>
    public AzureRmWebAppDeploymentPublishProfileTask(
        AdoExpression<string> publishProfilePath,
        AdoExpression<string> publishProfilePassword,
        AdoExpression<string> package)
        : base(AzureAppServiceConnectionType.PublishProfile)
    {
        PublishProfilePath = publishProfilePath;
        PublishProfilePassword = publishProfilePassword;
        Package = package;
    }
}

/// <summary>
/// Deploys to Azure App Service using an Azure Resource Manager service connection (<c>ConnectionType: AzureRM</c>).
/// More details can be found in the <see href="https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v5?view=azure-pipelines">official Azure DevOps pipelines documentation</see>.
/// </summary>
public abstract record AzureRmWebAppDeploymentAzureRmTask : AzureRmWebAppDeploymentTask
{
    /// <summary>
    /// Required. Azure Resource Manager subscription (service connection) used for the deployment.
    /// The official input name is <c>ConnectedServiceName</c>; <c>azureSubscription</c> is its documented YAML alias.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? AzureSubscription
    {
        get => GetExpression<string>("azureSubscription");
        init => SetProperty("azureSubscription", value);
    }

    /// <summary>
    /// Required. Name of an existing Azure App Service.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? WebAppName
    {
        get => GetExpression<string>("WebAppName");
        init => SetProperty("WebAppName", value);
    }

    /// <summary>
    /// Optional. Default value: <c>false</c>. Deploys to an existing deployment slot or Azure App Service Environment.
    /// For both targets, <see cref="ResourceGroupName"/> is required.
    /// The official input name is <c>DeployToSlotOrASEFlag</c>; <c>deployToSlotOrASE</c> is its documented YAML alias.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<bool>? DeployToSlotOrASE
    {
        get => GetExpression<bool>("deployToSlotOrASE", false);
        init => SetProperty("deployToSlotOrASE", value);
    }

    /// <summary>
    /// Required when <c>deployToSlotOrASE = true</c>. Azure resource group that contains the App Service specified above.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? ResourceGroupName
    {
        get => GetExpression<string>("ResourceGroupName");
        init => SetProperty("ResourceGroupName", value);
    }

    /// <summary>
    /// Required when <c>deployToSlotOrASE = true</c>. Existing slot other than the production slot.
    /// Default value: <c>production</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? SlotName
    {
        get => GetExpression<string>("SlotName");
        init => SetProperty("SlotName", value);
    }

    /// <summary>
    /// Optional. Web app application settings following the syntax <c>-key value</c>.
    /// Values containing spaces have to be enclosed in double quotes, for example <c>-Port 5000 -WEBSITE_TIME_ZONE "Eastern Standard Time"</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? AppSettings
    {
        get => GetExpression<string>("AppSettings");
        init => SetProperty("AppSettings", value);
    }

    /// <summary>
    /// Optional. Web app configuration settings following the syntax <c>-key value</c>.
    /// Values containing spaces have to be enclosed in double quotes, for example <c>-phpVersion 5.6 -linuxFxVersion: node|6.11</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? ConfigurationSettings
    {
        get => GetExpression<string>("ConfigurationSettings");
        init => SetProperty("ConfigurationSettings", value);
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="AzureRmWebAppDeploymentAzureRmTask"/> class with required properties.
    /// </summary>
    /// <param name="azureSubscription">Azure Resource Manager subscription (service connection) used for the deployment.</param>
    /// <param name="webAppName">Name of an existing Azure App Service.</param>
    protected AzureRmWebAppDeploymentAzureRmTask(AdoExpression<string> azureSubscription, AdoExpression<string> webAppName)
        : base(AzureAppServiceConnectionType.AzureRM)
    {
        AzureSubscription = azureSubscription;
        WebAppName = webAppName;
    }
}

/// <summary>
/// Deploys a package or folder to Azure App Service, for example a web app, an API app, a mobile app or a function app.
/// Use <see cref="AzureRmWebAppDeploymentContainerTask"/> for the container based app types.
/// More details can be found in the <see href="https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v5?view=azure-pipelines">official Azure DevOps pipelines documentation</see>.
/// </summary>
public record AzureRmWebAppDeploymentPackageTask : AzureRmWebAppDeploymentAzureRmTask
{
    /// <summary>
    /// Required. Type of the App Service the package is deployed to. Default value: <c>webApp</c>.
    /// The official input name is <c>WebAppKind</c>; <c>appType</c> is its documented YAML alias.
    /// </summary>
    [YamlIgnore]
    public AzureAppServicePackageAppType AppType
    {
        get => GetEnum("appType", AzureAppServicePackageAppType.WebApp);
        private init => SetProperty("appType", value);
    }

    /// <summary>
    /// Optional. Use when the app type is neither a Linux nor a function app. Name of the virtual application
    /// that has been configured in the Azure portal. The option is not required for deployments to the App Service root.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? VirtualApplication
    {
        get => GetExpression<string>("VirtualApplication");
        init => SetProperty("VirtualApplication", value);
    }

    /// <summary>
    /// Optional. Use when <c>appType = webAppLinux</c>. Framework and version of the web app,
    /// for example <c>DOTNETCORE|8.0</c>, <c>NODE|20-lts</c>, <c>PYTHON|3.12</c>, <c>PHP|8.3</c>, <c>JAVA|17-java17</c> or <c>TOMCAT|10.1-java17</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? RuntimeStack
    {
        get => GetExpression<string>("RuntimeStack");
        init => SetProperty("RuntimeStack", value);
    }

    /// <summary>
    /// Optional. Use when <c>appType = functionAppLinux</c>. Framework and version of the function app,
    /// for example <c>DOTNET|3.1</c>, <c>JAVA|11</c>, <c>NODE|22</c> or <c>PYTHON|3.8</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? RuntimeStackFunction
    {
        get => GetExpression<string>("RuntimeStackFunction");
        init => SetProperty("RuntimeStackFunction", value);
    }

    /// <summary>
    /// Optional. Use when <c>appType = webAppLinux || appType = functionAppLinux</c>.
    /// Start up command of the app, for example <c>dotnet exec filename.dll</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? StartupCommand
    {
        get => GetExpression<string>("StartupCommand");
        init => SetProperty("StartupCommand", value);
    }

    /// <summary>
    /// Optional. Customizes the deployment by running a script on the Azure App Service once the deployment has completed successfully.
    /// Use <see cref="InlineScript"/> or <see cref="ScriptPath"/> to provide the script itself.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<AzureAppServiceDeploymentScriptType>? ScriptType
    {
        get => GetExpression<AzureAppServiceDeploymentScriptType>("ScriptType");
        init => SetProperty("ScriptType", value);
    }

    /// <summary>
    /// Required when <c>ScriptType = Inline Script</c>. Deployment commands to run on the App Service, one command per line.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? InlineScript
    {
        get => GetExpression<string>("InlineScript");
        init => SetProperty("InlineScript", value);
    }

    /// <summary>
    /// Required when <c>ScriptType = File Path</c>. Path of the deployment script to run on the App Service.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? ScriptPath
    {
        get => GetExpression<string>("ScriptPath");
        init => SetProperty("ScriptPath", value);
    }

    /// <summary>
    /// Optional. Default value: <c>false</c>. When <c>false</c>, the best deployment method is auto-detected based on the app type,
    /// package format and other parameters. Set to <c>true</c> to choose the deployment method using <see cref="DeploymentMethod"/>.
    /// Not supported for Linux app types or <c>.war</c> and <c>.jar</c> packages.
    /// The official input name is <c>UseWebDeploy</c>; <c>enableCustomDeployment</c> is its documented YAML alias.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<bool>? UseCustomDeployment
    {
        get => GetExpression<bool>("enableCustomDeployment", false);
        init => SetProperty("enableCustomDeployment", value);
    }

    /// <summary>
    /// Required when <c>enableCustomDeployment = true</c>. Deployment method used for the app. Default value: <c>webDeploy</c>.
    /// The official input name is <c>DeploymentType</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<AzureAppServiceDeploymentMethod>? DeploymentMethod
    {
        get => GetExpression<AzureAppServiceDeploymentMethod>("DeploymentType");
        init => SetProperty("DeploymentType", value);
    }

    /// <summary>
    /// Optional. Use when <c>enableCustomDeployment = true &amp;&amp; DeploymentType != runFromZip</c>. Default value: <c>true</c>.
    /// Takes the App Service offline by placing an <c>app_offline.htm</c> file in its root directory before the sync operation begins.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<bool>? TakeAppOffline
    {
        get => GetExpression<bool>("TakeAppOfflineFlag", true);
        init => SetProperty("TakeAppOfflineFlag", value);
    }

    /// <summary>
    /// Optional. Use when <c>enableCustomDeployment = true &amp;&amp; DeploymentType = webDeploy</c>.
    /// Location of the <c>SetParameters.xml</c> file to use.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? SetParametersFile
    {
        get => GetExpression<string>("SetParametersFile");
        init => SetProperty("SetParametersFile", value);
    }

    /// <summary>
    /// Optional. Use when <c>enableCustomDeployment = true &amp;&amp; DeploymentType = webDeploy</c>. Default value: <c>false</c>.
    /// Deletes files on the App Service that have no matching files in the package or folder.
    /// This also removes all files related to any extension installed on the App Service.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<bool>? RemoveAdditionalFiles
    {
        get => GetExpression<bool>("RemoveAdditionalFilesFlag", false);
        init => SetProperty("RemoveAdditionalFilesFlag", value);
    }

    /// <summary>
    /// Optional. Use when <c>enableCustomDeployment = true &amp;&amp; DeploymentType = webDeploy</c>. Default value: <c>true</c>.
    /// Prevents files in the <c>App_Data</c> folder from being deployed to or deleted from the App Service.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<bool>? ExcludeFilesFromAppData
    {
        get => GetExpression<bool>("ExcludeFilesFromAppDataFlag", true);
        init => SetProperty("ExcludeFilesFromAppDataFlag", value);
    }

    /// <summary>
    /// Optional. Use when <c>enableCustomDeployment = true &amp;&amp; DeploymentType = webDeploy</c>.
    /// Additional Web Deploy arguments following the syntax <c>-key:value</c>,
    /// for example <c>-disableLink:AppPoolExtension -disableLink:ContentExtension</c>.
    /// Default value: <c>-retryAttempts:6 -retryInterval:10000</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? AdditionalArguments
    {
        get => GetExpression<string>("AdditionalArguments");
        init => SetProperty("AdditionalArguments", value);
    }

    /// <summary>
    /// Optional. Use when <c>enableCustomDeployment = true &amp;&amp; DeploymentType = webDeploy</c>. Default value: <c>true</c>.
    /// Enables the msdeploy flag <c>MSDEPLOY_RENAME_LOCKED_FILES=1</c> in the App Service application settings
    /// so that msdeploy can rename files that are locked during the deployment.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<bool>? RenameFiles
    {
        get => GetExpression<bool>("RenameFilesFlag", true);
        init => SetProperty("RenameFilesFlag", value);
    }

    /// <summary>
    /// Required when <c>appType = webAppLinux</c>. Deployment method used for Linux web apps. Default value: <c>oneDeploy</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<AzureAppServiceLinuxDeploymentMethod>? DeploymentMethodLinux
    {
        get => GetExpression<AzureAppServiceLinuxDeploymentMethod>("DeploymentTypeLinux");
        init => SetProperty("DeploymentTypeLinux", value);
    }

    /// <summary>
    /// Optional. Use when <c>appType = webAppLinux &amp;&amp; DeploymentTypeLinux = oneDeploy</c>. Default value: <c>true</c>.
    /// Performs a complete sync (clean) deployment.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<bool>? CleanDeployment
    {
        get => GetExpression<bool>("CleanDeploymentFlag", true);
        init => SetProperty("CleanDeploymentFlag", value);
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="AzureRmWebAppDeploymentPackageTask"/> class with required properties.
    /// </summary>
    /// <param name="azureSubscription">Azure Resource Manager subscription (service connection) used for the deployment.</param>
    /// <param name="webAppName">Name of an existing Azure App Service.</param>
    /// <param name="package">File path to the package or a folder containing the App Service contents.</param>
    /// <param name="appType">Type of the App Service the package is deployed to.</param>
    public AzureRmWebAppDeploymentPackageTask(
        AdoExpression<string> azureSubscription,
        AdoExpression<string> webAppName,
        AdoExpression<string> package,
        AzureAppServicePackageAppType appType = AzureAppServicePackageAppType.WebApp)
        : base(azureSubscription, webAppName)
    {
        AppType = appType;
        Package = package;
    }
}

/// <summary>
/// Deploys a container image to Azure App Service (Web App or Function App for Containers).
/// More details can be found in the <see href="https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v5?view=azure-pipelines">official Azure DevOps pipelines documentation</see>.
/// </summary>
public record AzureRmWebAppDeploymentContainerTask : AzureRmWebAppDeploymentAzureRmTask
{
    /// <summary>
    /// Required. Type of the App Service the container image is deployed to.
    /// The official input name is <c>WebAppKind</c>; <c>appType</c> is its documented YAML alias.
    /// </summary>
    [YamlIgnore]
    public AzureAppServiceContainerAppType AppType
    {
        get => GetEnum("appType", AzureAppServiceContainerAppType.WebAppContainer);
        private init => SetProperty("appType", value);
    }

    /// <summary>
    /// Required. Globally unique top-level domain name of the registry or namespace.
    /// The fully qualified image name has the format <c>&lt;registry or namespace&gt;/&lt;repository&gt;:&lt;tag&gt;</c>,
    /// for example <c>myregistry.azurecr.io/nginx:latest</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? DockerNamespace
    {
        get => GetExpression<string>("DockerNamespace");
        init => SetProperty("DockerNamespace", value);
    }

    /// <summary>
    /// Required. Name of the repository where the container images are stored.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? DockerRepository
    {
        get => GetExpression<string>("DockerRepository");
        init => SetProperty("DockerRepository", value);
    }

    /// <summary>
    /// Optional. Tag that the registry uses to give the container image a version, for example <c>latest</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? DockerImageTag
    {
        get => GetExpression<string>("DockerImageTag");
        init => SetProperty("DockerImageTag", value);
    }

    /// <summary>
    /// Optional. Start up command of the container, for example <c>dotnet exec filename.dll</c>.
    /// </summary>
    [YamlIgnore]
    public AdoExpression<string>? StartupCommand
    {
        get => GetExpression<string>("StartupCommand");
        init => SetProperty("StartupCommand", value);
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="AzureRmWebAppDeploymentContainerTask"/> class with required properties.
    /// </summary>
    /// <param name="azureSubscription">Azure Resource Manager subscription (service connection) used for the deployment.</param>
    /// <param name="webAppName">Name of an existing Azure App Service.</param>
    /// <param name="dockerNamespace">Globally unique top-level domain name of the registry or namespace.</param>
    /// <param name="dockerRepository">Name of the repository where the container images are stored.</param>
    /// <param name="appType">Type of the App Service the container image is deployed to.</param>
    public AzureRmWebAppDeploymentContainerTask(
        AdoExpression<string> azureSubscription,
        AdoExpression<string> webAppName,
        AdoExpression<string> dockerNamespace,
        AdoExpression<string> dockerRepository,
        AzureAppServiceContainerAppType appType = AzureAppServiceContainerAppType.WebAppContainer)
        : base(azureSubscription, webAppName)
    {
        AppType = appType;
        DockerNamespace = dockerNamespace;
        DockerRepository = dockerRepository;
    }
}

/// <summary>
/// Allowed values for the Azure App Service deploy task <c>ConnectionType</c> input.
/// </summary>
public enum AzureAppServiceConnectionType
{
    /// <summary>
    /// Default. Azure Resource Manager service connection.
    /// </summary>
    [YamlMember(Alias = "AzureRM")]
    AzureRM,

    /// <summary>
    /// Publish profile created in Visual Studio.
    /// </summary>
    [YamlMember(Alias = "PublishProfile")]
    PublishProfile,
}

/// <summary>
/// Allowed values for the Azure App Service deploy task <c>appType</c> input when a package or folder is deployed.
/// </summary>
public enum AzureAppServicePackageAppType
{
    /// <summary>
    /// Default. Web App on Windows.
    /// </summary>
    [YamlMember(Alias = "webApp")]
    WebApp,

    /// <summary>
    /// Web App on Linux.
    /// </summary>
    [YamlMember(Alias = "webAppLinux")]
    WebAppLinux,

    /// <summary>
    /// Function App on Windows. Not recommended, use the Azure Functions task instead.
    /// </summary>
    [YamlMember(Alias = "functionApp")]
    FunctionApp,

    /// <summary>
    /// Function App on Linux. Not recommended, use the Azure Functions task instead.
    /// </summary>
    [YamlMember(Alias = "functionAppLinux")]
    FunctionAppLinux,

    /// <summary>
    /// API App.
    /// </summary>
    [YamlMember(Alias = "apiApp")]
    ApiApp,

    /// <summary>
    /// Mobile App.
    /// </summary>
    [YamlMember(Alias = "mobileApp")]
    MobileApp,
}

/// <summary>
/// Allowed values for the Azure App Service deploy task <c>appType</c> input when a container image is deployed.
/// </summary>
public enum AzureAppServiceContainerAppType
{
    /// <summary>
    /// Default. Web App for Containers (Linux).
    /// </summary>
    [YamlMember(Alias = "webAppContainer")]
    WebAppContainer,

    /// <summary>
    /// Web App for Containers (Windows).
    /// </summary>
    [YamlMember(Alias = "webAppHyperVContainer")]
    WebAppHyperVContainer,

    /// <summary>
    /// Function App for Containers (Linux). Not recommended, use the Azure Functions for container task instead.
    /// </summary>
    [YamlMember(Alias = "functionAppContainer")]
    FunctionAppContainer,
}

/// <summary>
/// Allowed values for the Azure App Service deploy task <c>DeploymentType</c> input.
/// </summary>
public enum AzureAppServiceDeploymentMethod
{
    /// <summary>
    /// Default. Web Deploy (msdeploy).
    /// </summary>
    [YamlMember(Alias = "webDeploy")]
    WebDeploy,

    /// <summary>
    /// Zip Deploy.
    /// </summary>
    [YamlMember(Alias = "zipDeploy")]
    ZipDeploy,

    /// <summary>
    /// Run From Package.
    /// </summary>
    [YamlMember(Alias = "runFromZip")]
    RunFromZip,
}

/// <summary>
/// Allowed values for the Azure App Service deploy task <c>DeploymentTypeLinux</c> input.
/// </summary>
public enum AzureAppServiceLinuxDeploymentMethod
{
    /// <summary>
    /// Default. One Deploy.
    /// </summary>
    [YamlMember(Alias = "oneDeploy")]
    OneDeploy,

    /// <summary>
    /// Zip Deploy.
    /// </summary>
    [YamlMember(Alias = "zipDeploy")]
    ZipDeploy,
}

/// <summary>
/// Allowed values for the Azure App Service deploy task <c>ScriptType</c> input (post deployment action).
/// </summary>
public enum AzureAppServiceDeploymentScriptType
{
    /// <summary>
    /// Inline script provided in the pipeline definition.
    /// </summary>
    [YamlMember(Alias = "Inline Script")]
    InlineScript,

    /// <summary>
    /// Path of a script file that is part of the deployed contents.
    /// </summary>
    [YamlMember(Alias = "File Path")]
    FilePath,
}
